### ISSUE TITLE
페이지 이동시 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#100]
(천재 우선 수정사항 - Jik-ji.cdbook_0.3.5)

페이지 이동시 오류 팝업창이 뜨고 확인 누르면 해당 페이지로 이동합니다.

![2](https://user-images.githubusercontent.com/20455074/33371432-0d0af668-d53e-11e7-8514-6802068d83e1.png)

기존 작업한 원본을 불러와도. 신규 버튼을 삽입해도 동일합니다.

**Comment by vulcan9** [comment]
오류 로그로 보면 jikji-Binder 쪽 오류 같습니다.
오류가 발생하는 상황을 재연할 수 있는 파일이나 정보가 좀더 필요합니다.
Binder쪽 오류라면 Binder 쪽 이슈로 옮겨주세요.

**Comment by vulcan9** [comment]
원인 :
페이지 이동 버튼을 누르면 angular 가 동작하는 중간에 (iframe)페이지가 이동하게 되는데 이때 angular의 클릭 작업은 아직 종결되지 않아 location.href 값을 정상적으로 참조하지 못해 에러가 발생하게 된다.

해결 : 
페이지 이동하는 API를 비동기로 호출하여 angular가 작업을 종료할 시간을 벌어준다.
```
setTimeout(function(){
    goPageAPI(pageNumber);
}, 0);
```

**Comment by vulcan9** [comment]
**0.3.11** 버전(이상)에서 처리(구현) 되었습니다.
