### ISSUE TITLE
실행후 일정 시간이 지난 후 경고창이 뜸

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#101]
(천재 우선 수정사항 - Jik-ji.cdbook_0.3.5)

파일을 한참 열어놓았다가 닫았을 때 뜨는 경고창이 뜹니다.

![3-1](https://user-images.githubusercontent.com/20455074/33371581-937db708-d53e-11e7-8065-5c360149042f.png)

![3-2](https://user-images.githubusercontent.com/20455074/33371587-9658be1e-d53e-11e7-9783-3c7b0f2637b6.png)

**Comment by vulcan9** [comment]
### 원인
- 윈도우 10에서 발견되었습니다.
- 디스크 공간이 부족할때 윈도우에서 자동으로 공간을 확보하는 과정에서 Temp 폴더내 파일 임의로 삭제되는 현상이 있습니다.
- 윈도우 10에서  `설정 > 시스템 > 저장공간 > 자동으로 공간을 확보하는 방법 변경 > 지금 공간 확보`를 실행하면 재연됩니다.

### 해결
- 임시 작업 폴더를 `TEMP (~/AppData/Local/Temp)` 폴더 에서 `APPDATA (~/AppData/Roaming)` 폴더로 바꾸었습니다.

**0.7.10** 버전(이상)에서 처리(구현) 되었습니다.
