### ISSUE TITLE
기존 파일 닫을 때 / 신규 파일 불러올 때 / 오디오 플레이어 삽입 후 에러 메시지

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#102]
(천재 우선 수정사항 - Jik-ji.cdbook_0.3.5)

 - 파일을 열어 작업하다 신규 파일을 불러오려고 기존 파일을 닫을 때 
 - 신규 파일을 불러올 때 
 - 오디오 플레이어 삽입 후

위의 경우에 자주 뜨는 듯도 합니다.

![4-1](https://user-images.githubusercontent.com/20455074/33371700-f11fe3c2-d53e-11e7-9f87-3eb05dfe90e7.png)

![4-2](https://user-images.githubusercontent.com/20455074/33371704-f37f8f96-d53e-11e7-9f74-a72e3a48213d.png)

**Comment by vulcan9** [comment]
재연할수 있는 좀 더 자세한 정보가 필요합니다.
특정 jik 파일에서 자주 발생하는 현상이면 해당 jik 파일을 볼 수 있으면 도움이 될것 같습니다.

**Comment by vulcan9** [comment]
추가로 업데이트되는 내용이 없어 해당 이슈를 닫습니다.
이슈가 해결되지 않았다면 reopen 하시기 바랍니다.
