### ISSUE TITLE
Object 복사/붙여넣기 후 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#103]
(천재 우선 수정사항 - Jik-ji.cdbook_0.3.5)

이미지 복사, 붙여 넣기 후 미리보기와 출판 실행시 아래와 같은 Alert창이 종종 뜹니다.

![5-1](https://user-images.githubusercontent.com/20455074/33371777-2bc362ce-d53f-11e7-8750-5969d87c550b.png)

![5-2](https://user-images.githubusercontent.com/20455074/33371782-2d20e88a-d53f-11e7-9850-868ab7c4c8d2.png)

![6](https://user-images.githubusercontent.com/20455074/33371871-6d941ac2-d53f-11e7-8e62-85712a35c481.png)

**Comment by vulcan9** [comment]
첫번째 alert이 복사, 붙여넣기, 미리보기중 어느 시점에 발생한 것인지 명확하지 않아 단정할 순 없지만,
아마 하위버전에서 작성된 jik 파일에서 이미 이미지 관련 데이터가 누락된 상태이기 때문일 수도 있을것 같습니다.
자세한건 해당 jik 파일을 받아보면 도움이 될것 같습니다.

**Comment by vulcan9** [comment]
추가로 업데이트되는 내용이 없어 해당 이슈를 닫습니다.
이슈가 해결되지 않았다면 reopen 하시기 바랍니다.
