### ISSUE TITLE
이북 목차 불러오기시 개선 방안 검토

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#104]
(천재 우선 수정사항 - Jik-ji.cdbook_0.3.5)

기존 버전툴에서 작업된 파일을 불러와 이북 목차와, 페이지 이미지 교체를 했는데 미리보기와, 출판 실행시 툴이 멈춰 버리고 종료도 안되는 현상 발생합니다.

**Comment by onlyeye26** [comment]
해당 이슈는 이북 목차 때문인 것으로 보입니다.
이북 목차에 현재 작업물에 없는 페이지(ex. 작업물은 10페이지까지만 존재하는데 불러온 목차에는 11페이지가 작성된 경우)가 존재하는 경우 출판이 진행되지 않는 문제입니다.
이와 관련한 사항은 사용자가 미리 인지하고 오류를 피해갈 수 있도록 수정 방안 검토가 필요해 보입니다.

**Comment by vulcan9** [comment]
위와 같은 목차 관련된 이슈 사항은 #78 이슈에 등록되어 있고, bug로 확인 되었습니다.
개발 일정에 따라 개선하도록 하겠습니다.
이후 의견은 #78 이슈 목록에서 진행해 주세요.
