### ISSUE TITLE
목차 편집기 입력창 안나옴

### ISSUE THREAD

**Issue by hi763** [vulcan9/jik-ji#111]
![image](https://user-images.githubusercontent.com/23732865/37377685-cd57d468-276e-11e8-8eb0-da9b15ac41bd.png)

목차 편집기 실행기 기존에는 목차를 입력할 수 있는 입력창이 제공되었던것으로 알고 있습니다.
확인해봐주세요

**Comment by vulcan9** [comment]
#80 nwJS 버전 업그레이드 (nwJS 0.28.1 버전으로 업데이트 적용) 작업으로 인해
nwJS에서 url 호출 관련 변경된 사항이 적용되지 않아 목차 편집기를 불러오지 못하는 현상입니다.

**0.4.5** 버전(이상)에서 처리(구현) 되었습니다.
