### ISSUE TITLE
저장 오류 확인

### ISSUE THREAD

**Issue by hi763** [vulcan9/jik-ji#113]
직지에서 수정을 한 후에 저장을 하려고 하니 이런 오류가 생겼습니다.
![image](https://user-images.githubusercontent.com/23732865/37751070-95db7948-2dd3-11e8-858e-4f535c69b620.png)

저작도구에서도 알림창이 뜨는데요 해당 화면은 캡쳐 하지 못했습니다.

**Comment by vulcan9** [comment]
에러 내용만 봐서는 저장할때가 아니라 복사하기 작업할때 발생된 내용인데요.
내용은 복사하려고 하는 element 데이터를 참조할 수 없어서 발생된건데요

보통 원인은 두가지로 예상됩니다.
- 이전 직지 버전에서 작성된 문서인 경우 지원되지 않는 기능의 데이터를 참조하려고 하는 경우 이에대한 방어 코드가 미처 구현되지 않았을 수 있습니다.
- 데이터를 참조하려는 타이밍이 적절하지 못한 경우 PC에 성능 따라 에러가 발생할 수 있습니다.

재연가능한 방법이나 jik 파일이 있으면 전달해 주시기 바랍니다.

**Comment by vulcan9** [comment]
같은 원인인지는 확실치 않으나 복사, 붙여넣기, undo, redo 를 반복하는 과정에서 비어있는 element 데이터가 발생되는 것을 확인 하였습니다.

**Comment by vulcan9** [comment]
#103  (Object 복사/붙여넣기 후 오류)번 이슈와 통합니다.
