### ISSUE TITLE
저장 오류 확인2

### ISSUE THREAD

**Issue by hi763** [vulcan9/jik-ji#114]
![image](https://user-images.githubusercontent.com/23732865/37887412-9107c166-30fc-11e8-837b-0b03521d75ff.png)

USB에서 직파일을 끌어서 열고, 다른 이름으로 저장시 해당 오류 메시지가 나타납니다.

**Comment by vulcan9** [comment]
전달받은 jik 파일로 테스트해보겠습니다.

**Comment by vulcan9** [comment]
전달받은 jik 파일로 테스트 결과 정상동작합니다.
재연되지 않습니다. 
상담 결과 복사&붙여넣기 이슈와 연관이 있는것 같아 이 이슈는 닫고,
#103  (Object 복사/붙여넣기 후 오류)번 이슈와 통합니다.
