### ISSUE TITLE
출판 유형을 옵션으로 추가

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jik-ji#118]
현재 지원되는 출판 기능
- Epub으로 출판
- Epub + 뷰어(Epub) 출판 (웹서버에서 동작)

다음 옵션에 따라 출판 유형을 선택할 수 있는 기능을 추가합니다.
- `EXE` : Jik-ji Binder 컨테이너와 함께 출판하여 Binder에서 실행되는 형태
- `WEB` : Epub 압축 해지된 상태로 출판. web 브라우져에서 실행되는 상태

Epub 형태로 뷰잉되는지 개별 페이지로 뷰잉되는지는 의견 수렴 후 결정.

**Comment by vulcan9** [comment]
출판 페이지 뷰잉 방법 결정 필요함
1. `WEB`에서 실행되는 컨텐츠를 출판할때 : 
웹브라우져에서 epub 뷰어를 통해 페이지를 볼수 있도록 뷰어가 포함되어야 할까요?
아니면 뷰어가 없는 개별 페이지들만(page.html 형태) 출판되면 될까요?
2. `EXE` (Binder)에서 실행되는 경우에도 epub 뷰어를 통해 페이지를 보도록 해야 되겠죠?

**Comment by seol104** [comment]
WEB에서 실행되는 컨텐츠를 출판할때 :
웹브라우져에서 epub 뷰어를 통해 페이지를 볼수 있도록 뷰어가 포함되어야 할까요?
 네..포함되어야 합니다.
아니면 뷰어가 없는 개별 페이지들만(page.html 형태) 출판되면 될까요?
2.EXE (Binder)에서 실행되는 경우에도 epub 뷰어를 통해 페이지를 보도록 해야 되겠죠?
네..맞습니다.

**Comment by vulcan9** [comment]
출판 옵션 구현할 내용입니다.

#### epub 출판하기
  - 구성 : `epub 압축 파일`
  - 결과물 :   *.epub

#### web 출판하기
  - 구성 : `epub 컨텐츠` + `epub 뷰어`
  - 결과물 :   *_web.zip

#### exe 출판하기
  - 구성 : `Jik-ji Binder` + `epub 컨텐츠` + `epub 뷰어`
  - 결과물 :   *_binder.zip

**Comment by vulcan9** [comment]
**0.5.6** 버전(이상)에서 처리(구현) 되었습니다.
