### ISSUE TITLE
페이지 위치 바꾸기

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jik-ji#12]
페이지의 위치 조정(페이지 재정렬),  페이지 인덱스(순서) 조정

**Comment by vulcan9** [comment]
현재 기능이 제공되고 있으나 드래그 방식으로 직관적으로 페이지 위치를 바꿀수 있도록 기능 개선이 필요함

**Comment by Soarts** [comment]
페이지를 여러 장 한번에 선택한 뒤 위치 바꾸는 기능 필요

**Comment by vulcan9** [comment]
여러 문서를 다중 선택하여 드래그 기능으로 페이지 위치를 바꾸는 기능이 추가되었습니다.

**0.3.7** 버전(이상)에서 처리(구현) 되었습니다.
