### ISSUE TITLE
스크립트 입력이 되지 않는 현상

### ISSUE THREAD

**Issue by hi763** [vulcan9/jik-ji#131]
1. 1page에 이벤트로 직접 스크립트 입력
 event-document- on load에서  add action - 스크립트 작성
 완료 후 

2. 2page(다른 페이지)에서 위와 동일한 순서로 스크립트 작성

경우1) 
=> 2page에 스크립트 추가 안됨
=> 1pgae에 기존 스크립트가 아닌 2page에 등록된 스크립트로 변경

경우2) 
=> 2page에 스크립트 추가 안됨
=> 1pgae에 기존 스크립트와 함께 2page에서 등록한 스크립트가 함께 보여짐

**Comment by vulcan9** [comment]
현상 확인되었습니다.

원인 : 
페이지 선택이 바뀔때 이벤트 창 정보를 갱신하지 못하는 것으로 확인 되었습니다.
페이지가 바뀔때, Element 선택 상태가 바뀔때마다 이벤트 창 정보를 갱신해 주어야 합니다.

다음 버전(0.7.x)에 수정 배포될 예정입니다.

**Comment by vulcan9** [comment]
**0.6.4** 버전(이상)에서 처리(구현) 되었습니다.
