### ISSUE TITLE
코드 입력 시 버튼에 텍스트가 가려지는 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#140]
**이슈 내용**
이벤트 - 스크립트 작성에서 우측 상단의 버튼이 텍스트를 가리는 현상이 있습니다.

**Screenshots**
![default](https://user-images.githubusercontent.com/20455074/49420754-540a0080-f7d0-11e8-84fd-0eb38f33ddbd.JPG)

**Comment by vulcan9** [comment]
다음과 같이 버튼을 상단으로 옮겨 처리하였습니다.
![20190419_135424](https://user-images.githubusercontent.com/5111882/56406120-c88a9b00-62aa-11e9-9c9e-2bfe3366b620.png)

**0.9.4** 버전(이상)에서 처리(구현) 되었습니다.
