### ISSUE TITLE
이미지 SVG 추가 기능

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#144]
이미지 item 삽입시 jpg나 png만 인식하고 있습니다.
svg도 추가할 수 있으면 좋을 것 같습니다.

**Comment by vulcan9** [comment]
삽입 가능한 이미지 종류가 추가 되었습니다. 
- 추가된 이미지 종류 : svg, gif, animation gif
- 이미지 요소로 추가하거나 페이지 배경으로 추가할 수 있습니다.

**0.8.5** 버전(이상)에서 처리(구현) 되었습니다.
