### ISSUE TITLE
프로그램 업데이터 적용 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#148]
현재 직지 바인더 exe에 개발되어 있는 업데이터 기능을 직지에 적용하려고 합니다.
관련하여 업데이터 및 직지에서 추가적인 개발이 필요할 것으로 보입니다.
기존 업데이터는 황이구 부장님이 개발을 하였었고,
관련하여 정리하여 말씀드리도록 하겠습니다.

**Comment by vulcan9** [comment]
#106 `(업데이트 알림기능)` 이슈로 통합합니다.
해당 이슈를 참고하시기 바랍니다.
