### ISSUE TITLE
업데이트 기능 개선 요청

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jik-ji#155]
직지 프로그램 업데이트시 설치 폴더를 지정하게 되어 있습니다.

"현재 설치된 폴더에 업데이트 하기" 메뉴가 추가로 있었으면 합니다.

제가 현재 설치된 폴더에 업데이트 하려고, 폴더를 지정하였더니
에러가 난 후 새 폴더에 설치가 되는 형태로 프로그램 동작하는 것처럼 보였습니다.

**Comment by vulcan9** [comment]
현재 실행중인 버전 폴더에 업데이트를 하려면 별도의 업데이트 전용 프로그램을 만들어야 합니다.
현재 업데이트 로직은 직지가 실행된 상태에서 업데이트가 진행되므로 현재 폴더내 파일은 OS에서 덮어쓰기나 삭제할 수 없기 때문입니다.

업데이트 로직에 대한 내용은 #106 `업데이트 알림 기능` 을 참고하세요.

**Comment by tovsoft** [comment]
나중에 서비스 오픈시 인스톨 쉴드로 패키징하는 방법을 생각해봐야겠네요.

감사합니다.
