### ISSUE TITLE
편의성을 고려한 기능들

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#25]
1. 단축키(삭제(delete), 복사(ctrl+c), 붙여넣기(ctrl+v), 전체선택(ctrl+a), 실행취소(ctrl+z) 등)
   <br>
2. 드래그로 여러 객체요소 선택하는 기능 있었으면 함.
   <br>
3. 다중선택(group) 했을 때 어느 객체가 선택되었는지 육안으로 표시되지 않아 불편함.
   <br>

**Comment by vulcan9** [comment]
각 기능별로 3개의 새로운 이슈로 등록했습니다.

- #68  단축키 기능 구현
- #69 드래그 영역으로 객체 선택
- #70 다중선택(group) 했을 때 객체 표시 개선
