### ISSUE TITLE
시작 페이지 임의 설정

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#27]
시작페이지를 1페이지가 아닌 다른 페이지로 임의로 넣는 기능

**Comment by vulcan9** [comment]
뷰어쪽 작업 내용인지 좀 불명확하네요
첫페이지를 지정해서 띄우려는 것인지 아니면... 뭘까요?

**Comment by Soarts** [comment]
9.28 DT식 통권을 통한 마이너스 페이지 적용 테스트를 마쳤습니다. 이후 계획은 재논의 예정입니다.

**Comment by vulcan9** [comment]
통권, 분권 처리 기능이 추가되었습니다.
**0.3.32** 버전(이상)에서 처리(구현) 되었습니다.
