### ISSUE TITLE
텍스트 입력박스 컴포넌트 삽입 기능

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#29]
book 열람자가 콘텐츠 내에 입력할 수 있는 텍스트 입력박스 삽입 기능 검토 필요(천재교육 문의)

**Comment by vulcan9** [comment]
입력박스를 삽입하는것은 가능합니다.
입력박스가 삽입되면서 어떤 인터렉션 설정도 필요할것 같은데 이부분에 대한 자세한 내용이 필요합니다.

**Comment by vulcan9** [comment]
#54번 이슈와 통합 합니다.
