### ISSUE TITLE
확대/축소 하단 버튼 클릭으로 적용 안되는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#299]
하단 참고 이미지에 빨간색 박스 친 부분의 버튼을 클릭했을 때 확대/축소가 적용이 되지 않습니다.

![image](https://user-images.githubusercontent.com/82875704/233019722-25e814f8-e278-40ba-b061-969102743681.png)

**Comment by vulcan9** [comment]
**3.2.5** 버전(이상)에서 처리(구현) 되었습니다.
확인 바랍니다
