### ISSUE TITLE
미리보기시 미리보기 뷰어에서 마지막에 보던 페이지 표시

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#30]

**Comment by vulcan9** [comment]
"미리보기시 무조건 첫페이지부터 나와서 불편함. 마지막에 보던 페이지가 미리보기에서도 처음에 나와야 할 듯" 이라고 요청이 들어옴

**Comment by vulcan9** [comment]
0.1.339 버전에서 기능 추가되었습니다.
