### ISSUE TITLE
텍스트박스 안의 텍스트 선택 후 폰트 크기 변경 시 적용이 되지 않는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#300]
텍스트박스 삽입 후 아래의 예시 이미지처럼 텍스트를 전체선택 후
폰트 크기를 변경했을 때 적용이 되지 않는 현상이 있습니다.

![image](https://user-images.githubusercontent.com/82875704/233021395-09b62357-c28d-4131-b749-07a2c042388a.png)

**Comment by vulcan9** [comment]
**3.2.5** 버전(이상)에서 처리(구현) 되었습니다.
확인 바랍니다
