### ISSUE TITLE
문서 변환 및 출판 시 포커싱이 틀어지는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#301]
1. 직지 실행 - 빈 프로젝트 만들기 - 문서 변환 - PDF 문서를 변환합니다.
2. 문서 변환은 해상도 150%, 200% 두 가지로 테스트 하였습니다.
3. 문서 변환 완료 후 편집 화면을 봤을 때 아래 캡쳐 이미지처럼 포커싱이 틀어져 있습니다.
![image](https://user-images.githubusercontent.com/82875704/235871604-8fd9347c-2800-4168-a801-2e8a3f3f7778.png)

4. 최초에 직지 실행 후 '문서 변환 프로젝트 만들기'로 프로젝트를 생성한 후 PDF를 변환했을 때는 포커싱이 잘 맞습니다.
5. 출판을 한 이후에도 포커싱이 틀어지는 현상이 있습니다.
![image](https://user-images.githubusercontent.com/82875704/235872227-51430dcc-35ef-4e5d-b431-5e785e1b50be.png)

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.2.11** 버전(이상)에서 처리(구현) 되었습니다.
