### ISSUE TITLE
C드라이브 외에 다른 드라이브에도 폴더 경로 지정 요청

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#302]
현재 직지 설치 후 프로젝트 폴더를 생성할 때 C드라이브나 바탕화면에만 폴더를 생성할 수 있게 되어 있습니다.
![image](https://user-images.githubusercontent.com/82875704/236096487-6416a248-324a-4bbd-bcda-ed1ddbada75b.png)

사용자의 편의성을 위해 다른 드라이브에도 생성할 수 있게 개선되어야 할 것 같습니다.

**Comment by vulcan9** [comment]
프로젝트 생성을 허용하지 않은 폴더는 다음과 같습니다.
* Windows 폴더 및 하위 폴더 : `C:/Windows`
* 프로그램 폴더 및 하위 폴더
  - `C:/Program Files (x86)`
  - `C:/Program Files`
* USER 폴더 및 하위 폴더
  - `C:/Users/<user~>`

USER 폴더 중 다음 폴더 및 하위 폴더는 프로젝트 생성을 허용함
* USER (DESKTOP) 폴더는 허용하지 않음
  - `C:/Users/<user~>/desktop`
* USER (DESKTOP) 폴더 이하는 허용
  - `C:/Users/<user~>/desktop/~`
* USER_PROJECT 폴더 이하는 허용
  - `C:/Users/pdi10/Jik-Ji Project`
* 나머지 USER 폴더 이하는 허용하지 않음

추가로 각 드라이브의 루트 폴더에서는 프로젝트를 바로 생성할 수 없음
* `C:/`, `D:/`, ...
* 드라이브 경로 아래 폴더 생성 후 사용할 수 있음

**Jik-ji_Editor_3.2.9** 버전(이상)에서 처리(구현) 되었습니다.
