### ISSUE TITLE
서식파일 열었을 때 페이지리스트의 썸네일이 제대로 보이지 않는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#303]
1. 프로젝트 -> 새로 만들기 -> 포토북A 열기 로 테스트 하였습니다.

2. 서식파일을 열었을 때 좌측 페이지리스트의 썸네일이 잘려서 나오는 현상이 있습니다.

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/fec37159-9585-4d0b-93b9-f97aa12c80f0)

**Comment by vulcan9** [comment]
윈도우의 다음 설정이 캡쳐 크기에 영향을 미칩니다.

* 디스프레이 설정
![image](https://github.com/vulcan9/jikji.editor/assets/5111882/19afb836-92f7-4788-bc05-801d11fc5ed6)

* 접근성 설정
![image](https://github.com/vulcan9/jikji.editor/assets/5111882/add4e067-6d24-4f29-bec1-733de7b45dcf)

위 설정이 모두 100% 이면 원본 크기대로 캡쳐가 됩니다.
위에 증상이 나타나는 PC의 경우 이 두개의 설정 중 하나가 100% 이상으로 설정되어 있을 가능성이 있습니다.

**Comment by vulcan9** [comment]
해당 설정 내용을 포함하여 캡쳐 크기가 결정되도록 수정되었습니다.
**3.2.8** 버전(이상)에서 처리(구현) 되었습니다.

기존 문제있는 프로젝트에서 썸네일을 갱신해주면 정상적인 크기로 다시 캡쳐됩니다
![image](https://github.com/vulcan9/jikji.editor/assets/5111882/01736a85-5097-4130-9d4e-ecf299729d88)

**Comment by vulcan9** [comment]
## 추가 정보

본 이슈는 이미지 캡쳐 과정에서 발생한 것으로 
* 캡쳐할 썸네일 크기가 윈도우 최소창 크기 `(120x30)` 보다 작아 이미지를 crop 해야하는 경우에 발생함
* crop할 사이즈에 윈도우스크린 해상도를 보정해주어 crop 해야함

해당 프로젝트의 경우
* 썸네일 제한이 `가로,세로 200px`로 설정되어져 있는데 `900x1600px 페이지` 사이즈를 캡쳐하려고함
* 썸네일 사이즈가 `112x200px`로 계산되어 윈도우 창 최소 크기보다 작으므로 crop 작업이 진행됨
* `Jik-ji_Editor_3.2.11` 부터 썸네일 크기 제한이 `300px`로 설정됨
