### ISSUE TITLE
서식파일을 불러왔을 때 편집창에서 이미지가 보이지 않는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#306]
직지 저작도구에서 기본으로 제공되는 기본 템플릿으로 교안 하나를 제작하여 관리자 페이지 -> 저작도구 서식파일 탭으로 등록 하였습니다.
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/94ecdd94-10e9-4e4b-8b93-07caee08c09b)

직지 저작도구 실행 후 새로 만들기 -> 새 프로젝트로 서식 열기를 실행했을 때 편집창에서 이미지가 보이지 않는 현상이 있습니다.
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/a03adf19-c2b1-4da2-8fd5-780d193b91c9)

해당 현상 테스트를 위해 jik파일을 다운 받아 jik파일 열기로 열었을 때는 해당 현상의 오류가 없습니다.
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/1ac0ec60-f67b-4733-bc22-2e9550a70a9c)

**Comment by vulcan9** [comment]
## JIK 파일 이력
해당 서식파일은 `Jik-Ji 0.15.12 (academy)` 버전에서 작성된 템플릿을 사용하여 제작된 것으로 보임
이후 본 이슈에 영향을 주는 구조 및 기능 업데이트가 있습니다.

* [Jik-ji_Editor_3.0.3](https://github.com/vulcan9/jikji.editor/releases/tag/Jik-ji_3.0.3a)
프로젝트 폴더 구조 변경으로 파일이름에 UID 사용하지 않음
share 식별자 추가 (`JIK 3 : 2.2.0~`)
템플릿, 컴포넌트에서 사용된 asset은 프로젝트 폴더의 _share 폴더에 유지하여 공통으로 사용함

* [Jik-ji_Editor_3.1.47](https://github.com/vulcan9/jikji.editor/releases/tag/Jik-ji_Editor_3.1.47)
JIK 파일을 서식 파일로 사용

## 문제 상황
서식파일의 경우 JIK 파일 원본을 사용하지 않고 `복제(duplicate, not copy)`하여 사용함

* 복제할때 에셋을 포함하여 각 요소들의(document, element, group...) UID를 모두 변경함
*  해당 프로젝트는 `3.0.3` 이전에 작성된 템플릿을 사용하므로 파일 이름에 UID를 사용중임
* UID 변경시 에셋 파일 경로에 포함된 UID 문자열까지 변경됨
* 데이터에서 파일 경로 (UID)는 변경되었지만 실제 (물리적) 파일 이름은 이전 UID로 되어있음

따라서, 파일 경로에 UID 형식의 이름이 포함된 에셋 파일들을  찾을 수 없음

## 문제 요약
* 해당 JIK 파일은 `3.0.3` 버전 이전에 제작된 템플릿을 사용하여 만들어진 프로젝트로  파일 이름에 UID를 사용중임
* `3.0.3` 이전 버전에서 작성되었더라도 하위 호환성 코드로 JIK, 템플릿, 컴포넌트로 사용하는데 문제는 없음
* 서식 파일로 사용하는 경우 복제 과정에서 UID 파일 이름이 문제가됨

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.2.15** 버전(이상)에서 처리(구현) 되었습니다.
