### ISSUE TITLE
이전버전에서 제작한 컴포넌트가 있는 jik파일을 열고, 디버깅 모드를 했을 때 오류 발생하는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#307]
이전버전에서 버튼 컴포넌트를 만들었던 직파일 페이지를 오랜만에 디버깅모드로 열었을때 오류가 발생하는 현상이 있습니다.
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/9d599ab3-b072-42f3-9d33-4945e1831ee2)

또한, 새로운 프로젝트에서 컴포넌트를 삽입 후 디버깅모드를 실행했을 때, 동일한 오류가 발생합니다.
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/2db2de95-4420-4669-9101-4126eb6c048e)

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/c230621c-3a47-4ca9-b0bc-dab386d76c0d)

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/a632c20a-0a6d-443f-84a9-fd74b03221d3)

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/35f9241d-7a02-41ee-a0a5-8321363199a0)

**Comment by vulcan9** [comment]
## 원인
* 레이아웃 관련된 속성 `(x, y, width, height)`을 API를 통해 변경할때 발생되는 Jik-ji API 실행 오류 입니다.
* element에 `over`, `down` 상태가 정의되지 않았을때에도 API가 해당 상태의 속성값을 업데이트하려고 시도하면서 `undefind` 오류가 발생하였습니다.

## 패치 방법
(곧 업데이트 할 예정이지만) 상태 이름을 명시하는 것으로 임시 패치할 수 있습니다.
```
button.y(yPosition, 'normal');
```

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.2.15** 버전(이상)에서 처리(구현) 되었습니다.

stateName이 명시된 set 작업인 경우 또는 state에 해당 속성값이 있는 경우에만 업데이트함
(속성값이 없으면 선행되는 state 값 사용하므로 업데이트 안함)
