### ISSUE TITLE
직지 인스톨 파일 사용권 계약 부분 글자 깨짐 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#309]
Jik-ji Editor Demo 인스톨 파일 실행 후 직지 설치할 때, 사용권 계약 부분의 글자가 깨져 있습니다.

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/ed2a969d-03dc-4560-b3a6-11d9ba4b16fc)

**Comment by vulcan9** [comment]
다음 인스톨 파일 배포시 수정될 예정입니다.

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.2.19** 버전(이상)에서 처리(구현) 되었습니다.
* EULA 텍스트 인코딩을 `utf-8`에서 `ansi`로 변경함
