### ISSUE TITLE
페이지 이미지 추출 출판 시 이미지 사이즈가 다른 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#310]
페이지 이미지 추출 옵션의 크기 제한을 2000px로 테스트 했을 때
![image](https://github.com/vulcan9/jikji.editor/assets/82875704/b50c43a8-9609-476c-afef-a7e63ea99365)

master 폴더와 user-capture-pages 폴더의 이미지 사이즈가 서로 다릅니다. 또한, user-capture-pages 폴더의 이미지는 가로로 잘려 나옵니다.

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/475b94df-6495-49a8-9578-f2d139061c04)

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/b26034bd-0efe-402b-bd3e-2c2b9923f6cf)

**Comment by vulcan9** [comment]
페이지 캡쳐에 두가지 문제가 발견되었습니다.
* 버그 1) 일부 페이지가 pdf 변환 전 페이지 사이즈로 캡쳐되는 현상
* 버그2) 캡쳐 이미지가 일괄적으로 잘려 나오는 현상

## 버그 1) 일부 페이지가 pdf 변환 전 페이지 사이즈로 캡쳐되는 현상

### 원인
* 여러 문서를 캡쳐하는 경우 성능을 위해 캡쳐에 사용된 창(`show: false`)을 닫지 않고 계속 사용함
* 마지막 페이지를 캡쳐한 후 창이 닫히지 않은 현상이 있었음
* 닫히지 않은 창에서 새로운 페이지를 로드해서 캡쳐함
* 창 사이즈는 바뀌지 않았음 (창이 열릴때 창 사이즈 지정함)

### 해결
* 마지막 페이지를 캡쳐한 후 창이 닫히히도록 수정함
* 캡쳐할때 창 사이즈를 체크하여 조정하도록 수정함

## 버그 2) 캡쳐 이미지가 일괄적으로 잘려 나오는 현상

### 원인
캡쳐할때 사용되는 창 사이즈가 Desktop screen 해상도 크기를 이상으로 열리지 않음
```
캡쳐 해야할 이미지 높이가 2000px 이면 (윈도우 devicePixelRatio를 120%로 가정했을때)
필요한 윈도우 창 높이: 2000px * devicePixelRatio (1.2) = 2400px
2400px의 창 높이로 띄워 준 후 캡쳐해야함 (실제로는 2000/1.2 ~ 약 1667px로 뜨지만 실제 크기는 2400px임)

--> 윈도우 해상도가 1920x1200인 PC에서 실제로 열린 창 높이는 대략 1220px을 넘지 않음 
```
따라서 스크롤로 가려지는 부분은 캡쳐되지 않아 이미지 하단부가 잘림 현상이 발생함
> 참고 devicePixelRatio 에 대한 다른 이슈 (#303 )

마찬가지로 윈도우 최소창 (대략 140x40 / devicePixelRatio ) 사이즈 보다 작은 크기로 추출하려고 하면 캡쳐된 이미지를 crop 해줘야함

### 해결
* 최대 창크기를 설정하면 screen 해상도 크기를 이상으로 창을 띄울 수 있음
* 윈도우 옵션으로 `max_width`, `max_height` 속성값을 충분히 큰값으로 설정함

> nwJS 0.70.0 이상 버전에서 `show: false` 옵션으로 창을 띄울때 `captureScreenshot` 기능은 동작하지 않음

**Comment by vulcan9** [comment]
## 추가된 기능

### 한 페이지 추출 테스트
전체 이미지 추출전 결과 이미지 품질을 먼저 확인해 보기 위해 옵션이 적용된 한페이지만 미리 추출할 수 있도록 함

![image](https://github.com/vulcan9/jikji.editor/assets/5111882/223842c9-d8d5-437e-82be-2370a987f7b0)

### 페이지 구간 설정
* 원하는 페이지만 추출할 수 있도록 구간 설정 기능을 추가함
* 구간 설정은 콤마`,` 와 하이픈`-` 조합으로  설정함
```
1, 3, 8-10       : 1, 3 페이지, 8~10 페이지 설정됨
-5, 6            : 1~5페이지, 6페이지 설정됨
2, 6-            : 2페이지, 6페이지부터 마지막 페이지까지 설정됨
```
![image](https://github.com/vulcan9/jikji.editor/assets/5111882/5ae168b0-4a3e-46f9-88f6-8d0b7bd36684)

### 파일 포맷 및 품질 설정 옵션
* 페이지 추출 포맷에 `jpg`, `webp` 이미지 형식이 추가되었음 (기존 `png`)
* `jpg`, `webp` 이미지 형식을 선택하면 품질을 설정할 수있음 (이미지 용량 작아짐)

![image](https://github.com/vulcan9/jikji.editor/assets/5111882/8bd824f3-d8c3-4b34-b8e7-dc4f84196048)

**Jik-ji_Editor_3.3.0** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.3.0** 버전(이상)에서 처리(구현) 되었습니다.
