### ISSUE TITLE
편집화면에서 컴포넌트의 요소들이 보이지 않는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jik-ji#312]
컴포넌트 중 드래그앤드롭, 비디오 롤플레이, 비디오 컨트롤러, 오디오 싱크, 오디오 컨트롤러를 삽입했을 때
편집화면에서 컴포넌트의 요소들이 보이지 않습니다.

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/a420d4d5-aa3e-41d4-af48-3c806d83d1bb)

페이지 디버깅, 뷰어 미리보기를 했을때는 잘 보여집니다.

![image](https://github.com/vulcan9/jikji.editor/assets/82875704/d48493e9-67af-4969-b53b-250d17566621)

**Comment by vulcan9** [comment]
단순 판별식 오류입니다
**Jik-ji_Editor_3.2.17** 버전(이상)에서 처리(구현) 되었습니다.
