### ISSUE TITLE
audio, video 플레이어 사이즈 관련 이슈

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#32]
해상도가 큰 페이지에서 매우 작게 보이는 문제.

아이디어 논의되어야 함.

**Comment by vulcan9** [comment]
문제 원인은 
뷰어의 스크린 사이즈가 대략 가로 세로 10100px  이라 가정하고
보여질 페이지의 용지 사이즈가 대략 가로 세로 2000px 이라고 가정하면
이 페이지는 뷰어에 표시될때 0.5 scale로 표시되게 됩니다.
따라서 페이지에 삽입된 컨트롤러도 이 스케일에 영향을 받기때문에 상대적으로 너무 작게 보일수가 있습니다.

**Comment by Soarts** [comment]
* audio, video 플레이어로써의 역할을 수행할 수 있는 컴포넌트형 객체를 제공하는 안.
 - 재생, 일시정지, 정지 버튼을 포함한 컴포넌트 형태로 제공.
 - 리사이징을 고려하여야 함.
 - 탐색 Bar는 제공이 어려우니, 이 컴포넌트는 버튼만 제공하는 것으로 함

**Comment by vulcan9** [comment]
#71 이슈를 먼저 구현하면 이 문제도 해결될것 같습니다.

**Comment by vulcan9** [comment]
( #71 ) 컴포넌트를 등록하여 사용하는 기능이 **0.2.5** 버전(이상)에서 처리(구현) 되었습니다.
audio, video 플레이어를 컴포넌트로 만들어 저작툴에 번들로 제공하는 작업에 대해서는 일정을 고려하여 다시 이야기 해야할것 같습니다.

**Comment by vulcan9** [comment]
**0.2.117** 버전(이상)에서 처리(구현) 되었습니다.
