### ISSUE TITLE
텍스트에서 배경색 및 글자색이 적용되지 않는 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#321]
삽입한 텍스트의 속성 중 배경색과 글자색이 적용되지 않습니다.

![image](https://github.com/vulcan9/jikji.editor/assets/20455074/2e4178d4-1fe9-463f-8688-d043f542fc73)
![image](https://github.com/vulcan9/jikji.editor/assets/20455074/2d45f5e8-fb1a-40c8-9066-986bdd48fe1e)

**Comment by onlyeye26** [comment]
3.3.16(Demo) 에서 진행한 테스트입니다.

https://github.com/vulcan9/jikji.editor/assets/20455074/73f740ce-8285-4f78-ae8a-4544c765cf59

**Comment by vulcan9** [comment]
## 원인

컬러픽커에서 변경된 색상 정보가 전달되지 않아 색상이 적용되지 않는 현상입니다.
![image](https://github.com/vulcan9/jikji.editor/assets/5111882/518bbad0-9175-43ff-a10d-14f66140489e)


## 증상

텍스트 박스 뿐만 아니라 컬러픽커를 사용하는 모든 기능에서 정상동작 하지 않습니다.

* 텍스트 박스 글자 색상 및 글자 배경색 편집 기능
* 입력 박스의 글꼴 색상 편집 기능
* 문서 배경색 편집 기능
* 기본 요소들의 속성창에서 배경색 편집 기능
* 선 스타일 색상 편집 기능
* 기타 컬러픽커와 연계된 기능들

**Comment by vulcan9** [comment]
## Jik-ji_Editor_3.3.17
해당 이슈는 패키징된 배포 버전에서만 발생하는 버그입니다.
  - `angular-spectrum-colorpicker` min 파일 생성 후 적용

**Comment by onlyeye26** [comment]
확인 완료했습니다.
