### ISSUE TITLE
pdf 변환 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#322]
기존 0.15.5버전에서는 잘 변환되던 pdf가 
3.3.5버전에서 배경이 사라지는 이슈가 있습니다.
최신인 3.3.16에서도 동일합니다.

0.15.5
![image](https://github.com/vulcan9/jikji.editor/assets/20455074/f3936a2e-61a1-41ef-bc88-087639e2eed1)
![image](https://github.com/vulcan9/jikji.editor/assets/20455074/8bc52bf2-7298-4c9c-b325-4e5062a69039)

3.3.16
![image](https://github.com/vulcan9/jikji.editor/assets/20455074/d76a8657-6ba0-4bd5-a982-708599ce43f6)
![image](https://github.com/vulcan9/jikji.editor/assets/20455074/087e21f5-198e-447b-b0f7-1c9a4d459f50)

해당 샘플 pdf도 함께 드립니다.
[예시.pdf](https://github.com/vulcan9/jikji.editor/files/14047726/default.pdf)

**Comment by vulcan9** [comment]
`ghostScript-9.19`버전에서 `ghostScript-9.56.1` 버전으로 교체 후 나타난 `ghostScript` 버그 입니다.

또한 문제가 발생한 pdf 파일을 svg 변환하면 이미지 누락 현상이 발생했습니다.  
이는 `poppler-23.01.0` 버전에서 발생한 버그입니다.

## Jik-ji_Editor_3.3.17
* pdf 변환 이슈 수정
  - `ghostScript 10.02.1` 업데이트
  - `poppler 24.02.0` 업데이트

**Comment by onlyeye26** [comment]
확인 완료했습니다.
