### ISSUE TITLE
이벤트 액션 레이어 항목 보이지 않는 현상

### ISSUE THREAD

**Issue by wjdtprP** [vulcan9/jik-ji#329]
이벤트 적용 시 액션 선택 후 레이어 항목이 보이지 않습니다.

**Comment by vulcan9** [comment]
3.3.28 버전에서 다음 내용 수정 중 버그 발생함
* 객체 탐색기에서 같은 이벤트 종류를 (선택)오갈때 세부내용이 업데이트 안되는 현상 수정

### 원인

처음 이벤트 데이터 생성할때 actionID 지정되지 않아 참조 오류 발생함

### 해결
**Jik-ji_Editor_3.3.29** 버전(이상)에서 처리(구현) 되었습니다.
