### ISSUE TITLE
미디어 재생 토글

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#33]
재생, 일지정지 반복 뿐 아니라
재생, 정지 반복 기능도 지원할 수 있는지?

**Comment by vulcan9** [comment]
이벤트 설정에서 미디어 속성 재설정으로 지원되고 있습니다.
보다 복잡한 인터렉션에 대해서는 UI툴에서는 한계가 있을수 있습니다.
때문에 스크립트를 직접 삽입하는 기능을 검토중에 있습니다.

**Comment by vulcan9** [comment]
stopAllSound 이벤트 액션 기능이 추가 되었습니다.
**0.1.554** 버전(이상)에서 처리(구현) 되었습니다.
