### ISSUE TITLE
설치파일 실행시 NSIS Error

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#336]
Jik-ji Editor 3.3.2-free (win x86).exe 설치파일 실행시 특정 컴퓨터에서 아래 에러 창이 뜨고 실행되지 않는 이슈입니다.

![image](https://github.com/user-attachments/assets/b7efde68-a737-45e9-aa37-650098e38746)

내부에서는 해당 현상이 없습니다.

추가 정보가 필요하시면 말씀 부탁드립니다.

**Comment by vulcan9** [comment]
> installer integrity check has failed.
> Common causes include incomplete download and damaged media.
> Contact the installer's author to obtain a new copy.

`Jik-ji Editor 3.3.2-free (win x86).exe` 설치파일이 여러 이유로 손상되었을 수 있습니다. 
* 전송 또는 다운로드 중 손상 또는 백신에 의한 손상
* 설치가 안되는 해당 설치 파일을 받아볼 수 있으면 좋겠습니다.  
* 설치 실패한 PC의 운영체제가 궁금합니다. 

문제가 발생한 exe 설치 파일이 다른 PC에서도 설치 실패한다면 손상된 파일일 가능성이 클것 같습니다.  
새로 다운로드 받아 설치해보면 좋을것 같습니다.

**Comment by onlyeye26** [comment]
exe 설치 파일이 전달되면서 오류가 났던 것으로 보입니다.
다시 받아서 실행시 잘 되어 해당 이슈 종료하겠습니다.
