### ISSUE TITLE
Border 메뉴

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#34]
1. 이미지 라운딩 
   라운딩 처리 될 수 있도록 작업 예정 / 선 두께가 0일 때도 border 메뉴 활성화
2. 오디오 플레이어
   테두리에 색을 줬을 때 플레이어와 맞지 않음.(플레이어 테두리 영역이랑 선두께가 맞지 않음)
3. 비디오 플레이어
   Borders 값 줘도 미리보기에서 반영 안됨.
4. 비디오 플레이어(추가)
   영상 배경색 외에 배경이미지 선택해서 poster 설정할 수 있으면 좋을 듯...

**Comment by vulcan9** [comment]
1번 라운딩 처리가 boder 설정 그룹에 포함되어 있어서 독립적으로 설정 불가능하게 되어 있네요
라운딩 기능 독립적으로 사용할 수 있도록 0.2 버전 마일스톤에 추가합니다.

**Comment by vulcan9** [comment]
**0.1.713** 버전(이상)에서 처리(구현) 되었습니다.
