### ISSUE TITLE
미디어 관련 action 기능 수정 / 추가

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#35]
1. 미디어 재설정 메뉴에서  current time 시,분,초 단위로 설정 가능하도록

2. 다른 미디어들을 모두 stop 시키는 액션 추가

3. 액션 / Fullscreen 모드 변경(only video) 적용 안됨.

4. 액션 / 미디어 속성값 재설정 – SRC는 경로 잡아 줘도 링크 안됨.

**Comment by vulcan9** [comment]
2번 "다른 미디어들을 모두 stop 시키는 액션 추가" 내용은 새로운 이슈로 분리합니다. #39

**Comment by vulcan9** [comment]
3번, 4번 이슈는 수정되었습니다.
**0.1.554** 버전(이상)에서 처리(구현) 되었습니다.

1번 이슈는 새로운 이슈로 재등록 하겠습니다.(#52)

**Comment by vulcan9** [comment]
미디어 속성 재설정 action에서 컨트롤러 감추기 기능 동작 안됨

**Comment by vulcan9** [comment]
미디어 속성 재설정 action에서 컨트롤러 감추기 기능 동작 안됨
**0.1.574** 버전(이상)에서 처리(구현) 되었습니다.
