### ISSUE TITLE
페이지 이동 액션

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#36]
페이지 jump, back. next

**Comment by vulcan9** [comment]
뷰어에서 페이지를 이동할 수도록 저작툴 action에서 기능을 연결해달라는 요청입니다. 
기록으로 남겨야 하니 요청 내용 자세히 써주세요.

**Comment by vulcan9** [comment]
이전 페이지, 다음 페이지, 지정한 페이지로 이동 Action이 추가 되었습니다.

**0.1.387** 버전(이상)에서 처리(구현) 되었습니다.
