### ISSUE TITLE
win7 환경에서 변환 시도시 api 오류 발생(Jik-ji_0.1.349-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#47]
![_0905](https://cloud.githubusercontent.com/assets/20292746/18239750/4818bcaa-7382-11e6-94c4-a1e33a852264.jpg)

- 천재교육으로부터 접수(16.9.5 / Jik-ji_0.1.349-chunjae 배포일)
- win7 환경에서 변환 시도시 발생(변환 되지 않음) 
  고객사 테스트 PC 4대중 2대에서 발생(전부 win7)

**Comment by vulcan9** [comment]
pdf에서 썸네일 추출할때 사용한 라이브러리에서 발생한 오류입니다.
라이브러리 호출 경로에 의한 문제인것 같습니다.
한글이나 특수문자 경로에 의한 문제는 아닌것으로 파악됩니다.

라이브러리에서 사용되는 명령어가 OS 환경변수에 등록되지 않았거나 등록됬더라도 같은 명령어가 충돌나서 리턴값이 달라지거나 하는 경우에 실행에러가 발생할 수 있습니다

이 경우는 라이브러리가 내부에서 또 다른 외부 라이브러리(gs)를 호출할때 경로가 맞지 않아서(환경변수에 등록되지않은채로 호출되어서) 발생한 에러인것 같습니다.

개발 환경에서는 현재 증상을 재연되지가 않으므로 위 내용 위주로 디버깅해서 패치하겠으니 테스트 바랍니다. (원인찾기 힘드네....)

**Comment by Soarts** [comment]
Jik-ji_0.1.362-chunjae 고객사 테스트 결과(9.9)
 - 여전히 안되는 자리에서는 안됨. (같은 오류창)
 - 되는 두자리가 있는데, 차이점이라면 되는 두자리는 64비트 운영체제, 안되는 자리는 32비트 운영체제임.

**Comment by vulcan9** [comment]
3rd part 라이브러리를 모두 32 bit로 맞추어서 다시 테스트 합니다.

**Comment by vulcan9** [comment]
64 bit용 3rd party 라이브러리가 잘못 배포된듯 합니다.
32 bit 용으로 맞추니 문제가 발생되지 않는다고 합니다.
