### ISSUE TITLE
웹페이지 링크 액션 사용시 Unexpected token s in JSON at position 0 오류 발생(ver. Jik-ji_0.1.436-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#48]
![unexpected](https://cloud.githubusercontent.com/assets/20292746/18702854/817661ac-801e-11e6-9f09-edf276115280.JPG)

- 저작도구 미리보기에서는 정상 동작함.
- 교사용CD 구조에서 실행시에만 발생
- 웹페이지 링크 액션이 걸린 객체 클릭시 페이지 우측 하단에 메시지 표시

**Comment by vulcan9** [comment]
**0.1.491** 버전(이상)에서 처리(구현) 되었습니다.
