### ISSUE TITLE
보이기/감추기 액션 / 미디어 재생 액션 동작하지 않음(ver. Jik-ji_0.1.436-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#49]
기존에 동작하던 액션 기능중
- 보이기/감추기 액션
- 미디어 액션 전체(재생, 멈춤, 일시정지, 토글, 속성값 재설정, Fullscreen 모드 변경)

동작하지 않음.

**Comment by vulcan9** [comment]
**0.1.503** 버전(이상)에서 처리(구현) 되었습니다.
