### ISSUE TITLE
pdf변환후 최초 출판시 멈추는 현상(프로그레스바 멈춤)(Jik-ji_0.1.505-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#50]
- 최초 미리보기, 출판시 발생
- 작업관리자를 통하여 저작도구를 종료하고 재실행하면 정상 동작함.

**Comment by vulcan9** [comment]
원인  : pdf파일 변환하여 임포트할때 검색을 위해 텍스트를 추출하게되는데,
이때 페이지에 아무런 텍스트가 없는 경우 undefined 값이 데이터에 들어가게되고,
결국 출판할때 없는 변수로 인식되어 에러 일으킴.

**0.1.511** 버전(이상)에서 처리(구현) 되었습니다.
