### ISSUE TITLE
이전 작업에서 추가한 이미지 객체가 불러오기시 일부 보여지지 않음(Jik-ji_0.1.505-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#51]
- 이전 작업에서 객체 추가후 불러오기 하면, 해당 객체는 존재하나, 링크한 이미지는 보여지지 않음
- 이 경우 해당 객체는 삭제할 수 없음

테스트 파일은 별도로 전달드리겠습니다.

**Comment by Soarts** [comment]
테스트 파일 별도 전달해드렸습니다.(scenice_2.jik)

**Comment by vulcan9** [comment]
1. **0.1.339**이후 버전에서 asset 리소스 관리를 위해 복사/붙여넣기한 이미지의 경우 사용회수를 카운팅하여 삭제하도록 기능이 개선되었습니다. 

2. 하지만 **0.1.339**버전에서는 이 카운팅 로직에 버그가 있어 위와같이 이미지가 정상 표시되지 않는 현상이 있었습니다.

3. **0.1.346**이후 버전에서 이문제는 해결 되었습니다.

해당 현상은 **0.1.339**버전에서 저장된 jik 파일로, 부정확한 카운팅 데이터로 인해 붙여넣기/삭제 과정중에 리소스에서 삭제되었을 가능성이 있을것 같습니다.
(실제로 전달 받은 테스트 파일에도 해당 이미지 파일 뿐만 아니라 저장된 관련 asset 데이터도 찾을수 없었습니다.)

새로운 버전에서 새로 작성한 문서에서는 아직 이런 현상이 발견되지 않고 있으므로 
일단 이 이슈는 새로운 사항이 추가될때까지 닫도록 하겠습니다.

새로운 사항이 발견되면 아래 댓글로 달아주시면 reOpen 하겠습니다.

**Comment by vulcan9** [comment]
**0.1.339** 이하 버전에서 저장된 jik 파일을 불러오기 할때 카운팅 데이터를 임의로 생성해서 넣어주는 로직을 추가했습니다.
대신, 에셋이 얼마나 많은 곳에 사용되었는지는 파악하기 힘드므로 충분히 큰 카운팅 값을 지정해 주었습니다.
따라서 이런 보정된 코드를 가지는 에셋을 삭제할때에는 리소스 까지는 삭제되지 않고 남아있게 됩니다.

**0.1.513** 버전(이상)에서 처리(구현) 되었습니다.
