### ISSUE TITLE
출판 정보 설정 - title 설정이 가능하도록 - ebook 실행시 제목표시줄에 title 표시

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#53]
교사용 cd -> launcher.exe -> ebook -> 상단 제목표시줄에 title이 표시되도록 했으면 함.

**Comment by vulcan9** [comment]
프로젝트 설정창에서 출판설정 내용을 만들때 title을 설정할수 있도록 하고,
출판 후 이를 적용할 수 있도록 Binder 프로젝트쪽에서도 처리해 주어야할듯 합니다.

**Comment by vulcan9** [comment]
**0.1.574** 버전(이상)에서 처리(구현) 되었습니다.
