### ISSUE TITLE
작업시 간헐적으로 왼쪽 페이지리스트 썸네일이 까맣게 변하고 클릭되지 않는 현상

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#58]
- 주로 객체를 복사 / 붙여넣기를 몇차례 하다보면 발생
 - 텍스트박스를 많이 만들었을 때 생긴다는 보고도 있음.
 - 이때 프로젝트를 저장하고 프로그램을 재시동 후에 다시 프로젝트를 불러오면 정상화됨.
 - 프로젝트를 닫기 전까지는 원상복구 되지 않아 작업에 불편함.

 - 참고 이미지(페이지리스트 가장 아래쪽에 있는 2개 페이지에서 현상 발견됨)
![k-2](https://cloud.githubusercontent.com/assets/20292746/19708974/cc452506-9b5d-11e6-9330-ef776cfb18f3.png)

**Comment by vulcan9** [comment]
+ 편집모드로 바뀔때 썸네일 창의 페이지 사이즈가 영향을 받아 변경(편집모드를 표시하기 위한 화면 업데이트)되기 때문에 현상 발생함
+ 편집모드로 바뀌는 현상을 일으키는 element 표시를 썸네일창에는 표시하지 않도록 수정함
+ 썸네일 창의 화면표시 방식 및 기능은 Milestone에 계획된 대로 수정될 예정임

**0.1.585** 버전(이상)에서 처리(구현) 되었습니다.
