### ISSUE TITLE
기존 버전에서 작업한 jik 불러올 시 용지 사이즈 바뀜.(Jik-ji_0.1.662-chunjae)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#59]
- 기존 버전에서 작업한 jik 불러올 시 처음 선택한 페이지는 용지사이즈가 width 1024로 변경되고,
  이후 다른 페이지를 선택하면 항상 width 1024 height 768로 변경, 고정됨.
![dlrj](https://cloud.githubusercontent.com/assets/20292746/19927366/c61120d8-a13c-11e6-801d-079cd3164c44.JPG)

**Comment by vulcan9** [comment]
현상 확인 되었습니다.

**Comment by vulcan9** [comment]
용지 사이즈가 속성창 바인딩에 의해 default 값으로 초기화되는 현상이 있었습니다.
**0.1.686** 버전(이상)에서 처리(구현) 되었습니다.
