### ISSUE TITLE
pdf 변환 페이지 외에 빈 페이지가 추가된 프로젝트에서도 썸네일이 전부 생성되도록

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#60]
- 사용자가 pdf를 추가하면, 해당 pdf에 대한 썸네일 정상 생성됨
- 사용자가 이 상태에서 빈 페이지를 추가하고, 새로운 pdf를 추가로 변환했을 때는 모든 페이지에 대한 썸네일이 전부 나오지 않아 불편함이 있음.

**Comment by vulcan9** [comment]
TODO : 
1. 배경 이미지를 수동으로 변경할때 썸네일 업데이트 기능
2. 배경 이미지가 용지 크기보다 클 경우 crop해야하는 문제
3. 편집도중 용지 크기를 변경한 경우 모든 썸네일 업데이트 문제
4. 편집도중 용지 크기를 변경한 경우 기존 capture된 이미지의 업데이트 문제, scale 계산 문제
5. 하위버전에서 작성된 jik 파일을 불러오기 할꼉우 썸네일 지원문제
6. 지속적인 화면 capture에 의한 퍼포먼스 문제

**Comment by vulcan9** [comment]
**0.1.707** 버전(이상)에서 처리(구현) 되었습니다.

5번 - 하위버전에서 작성된 jik 파일을 불러오기 할경우 썸네일 지원문제는 구현되지 않았습니다.
하위 버전에서 작성된 문서에 썸네일까지 자동으로 지원되도록 하려면 별도의 컨버팅 프로그램을 제작해서 배포하는 것이 더 나아보입니다. 
현재는 하위버전에서 생성된 문서가 정상작동 하는것으로 구현 범위를 제한하였습니다.
