### ISSUE TITLE
Jik-Ji에서 [native] Fullscreen 화면 전환 (toggle) 액션 삽입시 오류

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji#63]
전체화면으로 바뀌고 난 후 클릭을 해도 원래 화면으로 돌아가지 않음. (원래 화면으로 돌아갈 방법이 없음)

**Comment by vulcan9** [comment]
jik-ji Binder에서 해결된것으로 보입니다.
확인 후 이슈 close 해주시기  바랍니다.
