### ISSUE TITLE
jik 파일을 불러온 뒤 작업을 하고 "저장"을 하면 작업이 정상적으로 덮어쓰기 안됨.

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#64]
테스트 방법
1. 기존 작업한 jik을 불러옴.(0.1.693 버전에서 작성한 프로젝트도 가능)
2. 변경 작업 진행(이미지 객체 위치 변경)
3. "저장" 클릭
4. 해당 프로젝트 다시 불러오면 작업 내용이 반영 되어있지 않음

**Comment by Soarts** [comment]
테스트 결과(11.14)

(변경) 기존 저작했던 경로를 jik에서 그대로 가지고 있어, 덮어쓰기 저장시 해당 경로로 자동 저장되도록 하고 있음. 사용자가 jik 파일의 위치를 바꾸거나, 다른 PC로 전송할 경우를 대비하여, jik을 불러올 때 jik 경로를 갱신해주어야 함.

**Comment by vulcan9** [comment]
**0.1.707** 버전(이상)에서 처리(구현) 되었습니다.
