### ISSUE TITLE
[Jik-ji API] Animation 객체 play() 관련

### ISSUE THREAD

**Issue by kenny14** [vulcan9/jik-ji#81]
$self.animation.enable(true);
$self.animation.config({
duration: 1,
timeFunction: 'ease',
delay:0
});

$self.animation.sequence()
.next({x: 300, y: 100})
.next({x: 600, y: 200})
.next({x: 900, y: 300})
.play();

이미지 엘리먼트에 위의 스크립트를 적용해봤는데요.
첫번째 x: 300, y: 100 만 실행되고 다음이 실행이 안되네요.

**Comment by vulcan9** [comment]
initialize이벤트 action에 작성했더니 동작이 안되는걸 확인 했습니다.
수정하도록 하겠습니다.

**Comment by vulcan9** [comment]
initialize 이벤트에서 실행될때 transition이 진행이 안되는 경우가 있는데,
초기화될때 첫번째 transition 상태값이 이미 적용되버리기 때문으로 보여집니다.
따라서 initialize 이벤트에서 play가 호출될때에는 delay를 두고 play 시켜주도록 수정되었습니다.

**0.3.8** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by vulcan9** [comment]
`3.0.38 ~3.1.39` 버전에서 animation API 동작 안함
* container의 layoutIsReady CSS 클래스에 의해 transition-property가 `opacity` 만으로 재정의되어 다른 속성에 대해서 동작하지 않았음

**3.1.40** 버전(이상)에서 처리(구현) 되었습니다.
