### ISSUE TITLE
jik-ji에서 출판시 페이지 섬네일 확장자가 jpg가 되어야 함.

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji#96]
* 버전 : jik-ji 0.3.0

* 현 버전으로 출판시 페이지 섬네일이 png 확장자로 나옵니다.
![image](https://user-images.githubusercontent.com/20292746/30412792-04acc26e-9955-11e7-88dc-8fcd5937792f.png)

* jpg 확장자여야 ebook 뷰어에서 정상 출력됩니다. 예전 버전에서는 jpg 확장자였던 것 같습니다.

**Comment by vulcan9** [comment]
**0.3.3** 버전(이상)에서 처리(구현) 되었습니다.
